// Project catalog data. Categories: Website, Mobile / App, IoT

const websiteNames = [
  "Smart College Management System",
  "AI-Based Student Performance Analyzer",
  "Online Examination Portal with Cheating Detection",
  "Placement Management System",
  "Smart Attendance Management",
  "Hostel Management System",
  "Library Management with AI Recommendations",
  "E-Learning Platform",
  "Online Course Marketplace",
  "Event & Seminar Management Portal",
  "Internship Finder Portal",
  "Resume Builder with AI Suggestions",
  "AI-Powered Career Guidance System",
  "Online Voting System",
  "Complaint Management Portal",
  "Smart Inventory Management",
  "Hospital Management System",
  "Blood Bank Management Portal",
  "Medicine Reminder Dashboard",
  "Hotel & Room Booking System",
  "Online Food Ordering System",
  "Real Estate Listing Portal",
  "Freelance Marketplace Platform",
  "AI Resume Screening System for Recruiters",
  "Online Bus Ticket Booking System",
  "Municipal Corporation Grievance Portal",
  "Farmer-to-Consumer E-Commerce Platform",
  "AI Legal Document Assistant",
  "Online Doctor Appointment System",
  "Bank Loan Eligibility Predictor",
  "E-Waste Collection & Recycling Portal",
  "College Alumni Networking Portal",
  "Smart Parking Management Website",
  "Insurance Policy Management System",
  "AI Chatbot for Customer Support",
  "Online Certificate Verification System",
  "Crowdfunding Platform for Startups",
  "Digital Library Card System",
  "AI-Based Fake News Detector",
  "Smart City Waste Management Dashboard",
  "Online Tutoring Marketplace",
  "AI Resume Ranking for HR Portals",
  "E-Governance Citizen Services Portal",
  "Restaurant Table Reservation System",
  "AI Sentiment Analysis Dashboard for Reviews",
  "Vehicle Rental Management System",
  "Property Tax Payment Portal",
  "AI-Based Plagiarism Checker",
  "Job Portal with AI Matching",
  "Smart Grievance Redressal System",
  "Multi-Vendor E-Commerce Website",
];

const mobileNames = [
  "AI-Based Fitness & Diet Tracker App",
  "Campus Navigation App with AR",
  "Smart Expense Tracker App",
  "AI Skin Disease Detection App",
  "Local Language Learning App",
  "AI-Powered Meditation & Sleep App",
  "Ride Sharing App for Students",
  "Grocery Delivery App with AI Suggestions",
  "AI Plant Disease Detection App",
  "Smart To-Do & Productivity App",
  "Parking Finder Mobile App",
  "AI Chat-Based Mental Health Companion",
  "Digital Wallet & Bill Split App",
  "AI-Based Attendance App with Face Recognition",
  "Home Service Booking App",
  "Lost & Found Campus App",
  "AI Recipe Recommendation App",
  "Second-Hand Book Exchange App",
  "AI-Based Resume Scanner App",
  "Smart Home Automation Controller App",
  "Blood Donor Finder App",
  "AI-Based Handwriting Recognition App",
  "Language Translator App with OCR",
  "Fitness Challenge Social App",
  "AI-Based Music Mood Recommender",
  "Campus Event Ticketing App",
  "Pet Care & Vet Appointment App",
  "AI-Based Sign Language Translator App",
  "Local Business Discovery App",
  "Daily Habit Tracker with AI Insights",
  "Freelancer Time Tracking App",
  "AI Voice Assistant for Elderly Care",
  "Carpooling App for Corporates",
  "AI-Based Currency Converter with OCR",
  "Digital Prescription & Pharmacy App",
  "Kids Learning & Quiz App",
  "AI Resume Builder Mobile App",
  "Smart Budgeting App for Students",
  "AI-Based Crop Health Scanner App",
  "Personal Safety & SOS Alert App",
  "Online Tuition Booking App",
  "AI Object Detection Shopping Assistant",
];

const iotNames = [
  "Smart Home Automation using IoT",
  "IoT-Based Smart Agriculture System",
  "Smart Traffic Management using IoT",
  "IoT-Based Air Quality Monitoring System",
  "Smart Waste Bin Monitoring System",
  "IoT-Based Health Monitoring Wearable",
  "Smart Irrigation System using IoT",
  "IoT-Based Fire & Gas Leak Detection",
  "Smart Energy Meter Monitoring System",
  "IoT-Based Vehicle Tracking System",
  "Smart Street Light Control System",
  "IoT-Based Smart Parking System",
  "Home Security System with IoT Camera Alerts",
  "IoT-Based Water Level Monitoring System",
  "Smart Attendance using RFID & IoT",
  "IoT-Based Weather Monitoring Station",
  "Smart Baby Cradle Monitoring System",
  "IoT-Based Soil Moisture & Crop Monitor",
  "Industrial IoT Machine Health Monitor",
];

const internshipNames = [
  "MERN Stack Developer Internship Project",
  "Python AI/ML Developer Internship Project",
  "Full Stack Web Development Internship Capstone",
  "Data Analytics Internship Project with Python",
  "Django REST API Internship Project",
  "React.js Frontend Development Internship Project",
  "Node.js Backend Development Internship Project",
  "AI Chatbot Development Internship Project",
  "Machine Learning Internship Capstone Project",
  "Cloud Deployment (AWS/Azure) Internship Project",
  "Cybersecurity Fundamentals Internship Project",
  "UI/UX Design Internship Portfolio Project",
];

function toCategoryList(names, category) {
  return names.map((name) => ({ name, category }));
}

const rawList = [
  ...toCategoryList(websiteNames, "Website"),
  ...toCategoryList(mobileNames, "Mobile / App"),
  ...toCategoryList(iotNames, "IoT"),
  ...toCategoryList(internshipNames, "Internship"),
];

export const projects = rawList.map((p, idx) => ({
  id: idx + 1,
  price: p.category === "Internship" ? "₹6,000" : "₹13,000",
  ...p,
}));

export const CATEGORIES = [
  { key: "All", label: "All", count: projects.length },
  {
    key: "Website",
    label: "Website",
    count: projects.filter((p) => p.category === "Website").length,
  },
  {
    key: "Mobile / App",
    label: "Mobile / App",
    count: projects.filter((p) => p.category === "Mobile / App").length,
  },
  {
    key: "IoT",
    label: "IoT",
    count: projects.filter((p) => p.category === "IoT").length,
  },
  {
    key: "Internship",
    label: "Internship Projects",
    count: projects.filter((p) => p.category === "Internship").length,
  },
];
