// Project catalog data. Categories: Website, Mobile / App, IoT, Internship

// ============ WEBSITE PROJECTS (150+) ============
const websiteNames = [
  // Management Systems
  "Smart College Management System",
  "AI-Based Student Performance Analyzer",
  "Online Examination Portal with Cheating Detection",
  "Placement Management System",
  "Smart Attendance Management",
  "Hostel Management System",
  "Library Management with AI Recommendations",
  "E-Learning Platform",
  "Online Course Marketplace",
  "Event & Seminar Management Portal",
  "Internship Finder Portal",
  "Resume Builder with AI Suggestions",
  "AI-Powered Career Guidance System",
  "Online Voting System",
  "Complaint Management Portal",
  "Smart Inventory Management",
  "Hospital Management System",
  "Blood Bank Management Portal",
  "Medicine Reminder Dashboard",
  "Hotel & Room Booking System",
  "Online Food Ordering System",
  "Real Estate Listing Portal",
  "Freelance Marketplace Platform",
  "AI Resume Screening System for Recruiters",
  "Online Bus Ticket Booking System",
  "Municipal Corporation Grievance Portal",
  "Farmer-to-Consumer E-Commerce Platform",
  "AI Legal Document Assistant",
  "Online Doctor Appointment System",
  "Bank Loan Eligibility Predictor",
  "E-Waste Collection & Recycling Portal",
  "College Alumni Networking Portal",
  "Smart Parking Management Website",
  "Insurance Policy Management System",
  "AI Chatbot for Customer Support",
  "Online Certificate Verification System",
  "Crowdfunding Platform for Startups",
  "Digital Library Card System",
  "AI-Based Fake News Detector",
  "Smart City Waste Management Dashboard",
  "Online Tutoring Marketplace",
  "AI Resume Ranking for HR Portals",
  "E-Governance Citizen Services Portal",
  "Restaurant Table Reservation System",
  "AI Sentiment Analysis Dashboard for Reviews",
  "Vehicle Rental Management System",
  "Property Tax Payment Portal",
  "AI-Based Plagiarism Checker",
  "Job Portal with AI Matching",
  "Smart Grievance Redressal System",
  "Multi-Vendor E-Commerce Website",
  "School Management System with Parent Portal",
  "Healthcare Appointment Scheduling System",
  "AI-Based Medical Diagnosis Support System",
  "Pharmacy Inventory Management System",
  "Clinical Trial Management Portal",
  "Patient Health Record System",
  "Telemedicine Consultation Platform",
  "Mental Health Therapy Booking System",
  "Vaccination Management Portal",
  "Organ Donation Registry System",
  "Blood Donation Campaign Management",
  "NGO Management & Donation Platform",
  "Disaster Management & Relief Portal",
  "Emergency Response Coordination System",
  "Volunteer Management Platform",
  "Community Service Hours Tracker",
  "Social Welfare Scheme Portal",
  "Public Grievance Tracking System",
  "RTI Application Management Portal",
  "Government Document Verification System",
  "Scholarship Management Portal",
  "Student Loan Application System",
  "Educational Resource Sharing Platform",
  "Online Coding Bootcamp Platform",
  "Technical Interview Preparation Portal",
  "Competitive Programming Dashboard",
  "Open Source Contribution Tracker",
  "Developer Portfolio Builder",
  "Code Review Collaboration Platform",
  "Bug Tracking & Issue Management System",
  "Project Management Tool for Teams",
  "Employee Leave Management System",
  "HR Recruitment & Onboarding Portal",
  "Payroll Management System",
  "Asset Tracking Management System",
  "Facility Booking & Reservation System",
  "Meeting Room Scheduling System",
  "Corporate Training & LMS Portal",
  "Employee Performance Review System",
  "Visitor Management System",
  "Security Incident Reporting Portal",
  "Compliance & Audit Management System",
  "Risk Assessment Dashboard",
  "Business Intelligence Dashboard",
  "Customer Relationship Management (CRM)",
  "Lead Generation & Tracking System",
  "Sales Pipeline Management Portal",
  "Invoice & Billing Management System",
  "Expense Reimbursement Portal",
  "Procurement Management System",
  "Supplier Management & Evaluation Portal",
  "Logistics & Supply Chain Dashboard",
  "Warehouse Management System",
  "Fleet Management System",
  "Fuel Monitoring & Optimization System",
  "Driver Performance & Safety Tracker",
  "Route Optimization & Planning Tool",
  "Shipment Tracking & Delivery Portal",
  "Courier Management System",
  "Retail Inventory & POS System",
  "Customer Feedback & Survey Platform",
  "Review Moderation & Analytics Dashboard",
  "Social Media Analytics Tool",
  "Content Management System (CMS)",
  "News Aggregator & Personalization Platform",
  "Podcast Hosting & Distribution Platform",
  "Video Streaming & Content Platform",
  "Live Streaming & Webinar Platform",
  "Virtual Event Management System",
  "Online Community & Forum Platform",
  "Knowledge Base & Documentation Portal",
  "Bug Bounty & Security Research Platform",
  "AI-Powered Resume Screening System",
  "Candidate Assessment & Testing Platform",
  "Online Skill Assessment Portal",
  "Certification & Badge Management System",
  "Learning Path & Curriculum Builder",
  "AI-Based Study Material Recommender",
  "Language Learning Platform",
  "Cultural Exchange & Language Practice Portal",
  "Recipe Sharing & Meal Planning Platform",
  "Diet & Nutrition Tracking System",
  "Personal Health & Fitness Dashboard",
  "Sports Tournament Management System",
  "Fantasy Sports League Platform",
  "Event Discovery & Booking Platform",
  "Concert & Festival Management System",
  "Art Gallery & Exhibition Portal",
  "Museum Virtual Tour Platform",
  "Historical Archive & Documentation System",
  "Book Review & Recommendation Portal",
  "Writing Portfolio & Publishing Platform",
  "Creative Writing Collaboration System",
  "Photography Portfolio & Selling Platform",
  "Design Showcase & Inspiration Gallery",
  "Interior Design Visualization Platform",
  "Architecture Project Management Portal",
  "Construction Project Tracking System",
  "Real Estate Property Valuation System",
  "Mortgage & Loan Comparison Platform",
  "Investment Portfolio Tracker",
  "Stock Market Analysis Dashboard",
  "Cryptocurrency Trading & Portfolio Manager",
  "Personal Finance Management System",
  "Budget Planning & Expense Tracker",
  "Subscription Management System",
  "Warranty & Insurance Claim Portal",
  "Product Recall & Safety Alert System"
];

// ============ MOBILE / APP PROJECTS (150+) ============
const mobileNames = [
  "AI-Based Fitness & Diet Tracker App",
  "Campus Navigation App with AR",
  "Smart Expense Tracker App",
  "AI Skin Disease Detection App",
  "Local Language Learning App",
  "AI-Powered Meditation & Sleep App",
  "Ride Sharing App for Students",
  "Grocery Delivery App with AI Suggestions",
  "AI Plant Disease Detection App",
  "Smart To-Do & Productivity App",
  "Parking Finder Mobile App",
  "AI Chat-Based Mental Health Companion",
  "Digital Wallet & Bill Split App",
  "AI-Based Attendance App with Face Recognition",
  "Home Service Booking App",
  "Lost & Found Campus App",
  "AI Recipe Recommendation App",
  "Second-Hand Book Exchange App",
  "AI-Based Resume Scanner App",
  "Smart Home Automation Controller App",
  "Blood Donor Finder App",
  "AI-Based Handwriting Recognition App",
  "Language Translator App with OCR",
  "Fitness Challenge Social App",
  "AI-Based Music Mood Recommender",
  "Campus Event Ticketing App",
  "Pet Care & Vet Appointment App",
  "AI-Based Sign Language Translator App",
  "Local Business Discovery App",
  "Daily Habit Tracker with AI Insights",
  "Freelancer Time Tracking App",
  "AI Voice Assistant for Elderly Care",
  "Carpooling App for Corporates",
  "AI-Based Currency Converter with OCR",
  "Digital Prescription & Pharmacy App",
  "Kids Learning & Quiz App",
  "AI Resume Builder Mobile App",
  "Smart Budgeting App for Students",
  "AI-Based Crop Health Scanner App",
  "Personal Safety & SOS Alert App",
  "Online Tuition Booking App",
  "AI Object Detection Shopping Assistant",
  "Mental Wellness & Journaling App",
  "Anxiety Management & Breathing Exercises",
  "Sleep Tracking & Smart Alarm App",
  "Hydration & Health Reminder App",
  "Calorie Counter & Macro Tracker App",
  "Workout Planner & Exercise Guide App",
  "Yoga & Meditation Class Booking App",
  "Sports Coaching & Training App",
  "Running & Marathon Tracker App",
  "Cycling Route Planner & Tracker App",
  "Swimming Performance Analyzer App",
  "Golf Swing Analyzer & Coach App",
  "Tennis Match Tracker & Coach App",
  "Cricket Score & Match Analyzer App",
  "Football Training & Skill Development App",
  "Basketball Stats Tracker App",
  "Volleyball Match Planner App",
  "Badminton Court Booking & Tournament App",
  "Table Tennis Score & Match Tracker App",
  "E-Sports Tournament Manager App",
  "Gaming Community & Events App",
  "Streaming & Content Creator App",
  "Video Editing & Effects App",
  "Photo Editing & Filter App",
  "Voice Changer & Effects App",
  "Music Production & Beat Maker App",
  "Podcast Recording & Editing App",
  "Audiobook Creator & Publisher App",
  "Story Writing & Novel Planner App",
  "Poetry & Creative Writing App",
  "Journal & Diary App with Mood Tracking",
  "Goal Setting & Achievement Tracker App",
  "Habit Formation & Streak Tracker App",
  "Focus & Productivity Timer App",
  "Screen Time & Digital Wellness App",
  "Parental Control & Monitoring App",
  "Family Locator & Safety App",
  "Couple Relationship & Anniversary Tracker App",
  "Friendship & Social Circle Manager App",
  "Networking & Professional Connect App",
  "Mentorship & Career Guidance App",
  "Skill Sharing & Learning Community App",
  "Volunteer & Community Service App",
  "Donation & Fundraising App",
  "Crowdfunding & Project Backing App",
  "Charity & Social Cause App",
  "Environmental Impact Tracker App",
  "Carbon Footprint Calculator App",
  "Sustainable Living & Eco Tips App",
  "Recycling & Waste Management App",
  "Energy Consumption Monitor App",
  "Water Usage & Conservation App",
  "Air Quality Monitor & Alert App",
  "Weather Forecast & Alerts App",
  "Earthquake Early Warning System App",
  "Flood Alert & Emergency App",
  "Wildlife Sighting & Tracking App",
  "Bird Watching & Identification App",
  "Plant & Flower Identification App",
  "Garden Planner & Care App",
  "Urban Farming & Grow Guide App",
  "Apartment & Rental Finder App",
  "House Hunting & Property App",
  "Interior Design & AR Furniture App",
  "DIY & Home Improvement App",
  "Car Maintenance & Service App",
  "Electric Vehicle Charging Finder App",
  "Parking Spot & Garage Rental App",
  "Airport & Flight Tracker App",
  "Train Schedule & Booking App",
  "Bus Route & Real-Time Tracker App",
  "Cab & Ride-Sharing App",
  "Bike Sharing & Rental App",
  "Scooter & EV Rental App",
  "Travel Planner & Itinerary Builder App",
  "Hotel & Accommodation Finder App",
  "Restaurant Discovery & Table Booking App",
  "Food Delivery & Takeout App",
  "Grocery Shopping & Delivery App",
  "Medicine Delivery & Health App",
  "Beauty & Salon Booking App",
  "Spa & Wellness Center App",
  "Barber & Grooming App",
  "Fashion & Wardrobe Manager App",
  "Clothing Swap & Thrift Store App",
  "Shoe Size & Fit Finder App",
  "Jewelry & Accessories App",
  "Home Decor & Furniture App",
  "Kitchen & Recipe App",
  "Baking & Cake Design App",
  "Coffee & Cafe Finder App",
  "Wine & Spirit Guide App",
  "Cocktail Mixer & Bartender App",
  "Hookah & Lounge Finder App",
  "Pub & Bar Locator App",
  "Nightlife & Club Event App"
];

// ============ IoT PROJECTS (100+) ============
const iotNames = [
  "Smart Home Automation using IoT",
  "IoT-Based Smart Agriculture System",
  "Smart Traffic Management using IoT",
  "IoT-Based Air Quality Monitoring System",
  "Smart Waste Bin Monitoring System",
  "IoT-Based Health Monitoring Wearable",
  "Smart Irrigation System using IoT",
  "IoT-Based Fire & Gas Leak Detection",
  "Smart Energy Meter Monitoring System",
  "IoT-Based Vehicle Tracking System",
  "Smart Street Light Control System",
  "IoT-Based Smart Parking System",
  "Home Security System with IoT Camera Alerts",
  "IoT-Based Water Level Monitoring System",
  "Smart Attendance using RFID & IoT",
  "IoT-Based Weather Monitoring Station",
  "Smart Baby Cradle Monitoring System",
  "IoT-Based Soil Moisture & Crop Monitor",
  "Industrial IoT Machine Health Monitor",
  "IoT-Based Smart Door Lock System",
  "Smart Refrigerator Inventory Monitor",
  "IoT Water Quality Monitoring System",
  "Smart Greenhouse Automation System",
  "IoT-Based Fish Farm Monitoring",
  "Smart Poultry Farm Management System",
  "IoT Dairy Farm Monitoring System",
  "Smart Beehive Monitoring System",
  "IoT-Based Forest Fire Detection",
  "Smart Avalanche Detection System",
  "IoT Earthquake Early Warning System",
  "Smart Bridge Structural Health Monitor",
  "IoT Building Energy Management System",
  "Smart Elevator Maintenance System",
  "IoT HVAC Optimization System",
  "Smart Lighting Control System",
  "IoT Conference Room Management",
  "Smart Office Occupancy System",
  "IoT Employee Health Tracker",
  "Smart PPE Compliance System",
  "IoT Emergency Alert System",
  "Smart Fire Escape Route System",
  "IoT Gas Cylinder Level Monitor",
  "Smart Water Heater Control System",
  "IoT Dishwasher Energy Optimizer",
  "Smart Washing Machine IoT System",
  "IoT Refrigerator Temperature Monitor",
  "Smart Oven & Cooking Assistant",
  "IoT Coffee Machine Controller",
  "Smart Vacuum Cleaner Robot",
  "IoT Garden Maintenance Robot",
  "Smart Pool Monitoring System",
  "IoT Spa & Jacuzzi Controller",
  "Smart Sauna Temperature System",
  "IoT Garage Door Opener System",
  "Smart Driveway Alert System",
  "IoT Mailbox Notification System",
  "Smart Pet Feeder & Water Dispenser",
  "IoT Pet Tracker & Health Monitor",
  "Smart Bird Feeder Camera System",
  "IoT Fish Tank Monitor & Feeder",
  "Smart Terrarium Climate Controller",
  "IoT Plant Watering & Care System",
  "Smart Hydroponic Monitoring System",
  "IoT Vertical Farm Controller",
  "Smart Mushroom Cultivation Monitor",
  "IoT Vineyard Monitoring System",
  "Smart Orchard Management System",
  "IoT Olive Grove Monitor",
  "Smart Tea Garden Management System",
  "IoT Coffee Plantation Monitor",
  "Smart Rubber Plantation System",
  "IoT Bamboo Farm Monitor",
  "Smart Timber Forest Management",
  "IoT Wildlife Tracking System",
  "Smart Marine Life Monitor",
  "IoT Coral Reef Health Monitor",
  "Smart Ocean Cleanup Drone System",
  "IoT Beach Erosion Monitor",
  "Smart Glacier Melting Monitor",
  "IoT Volcano Activity Monitor",
  "Smart Desertification Monitor",
  "IoT Pollution Source Tracker",
  "Smart Noise Pollution Monitor",
  "IoT Radiation Detection System",
  "Smart Chemical Leak Detector",
  "IoT Oil Spill Detection System",
  "Smart Pipeline Monitoring System",
  "IoT Power Grid Monitoring System",
  "Smart Substation Monitor",
  "IoT Transformer Health Monitor",
  "Smart Solar Panel Optimizer",
  "IoT Wind Turbine Performance Monitor",
  "Smart Hydroelectric Plant Monitor",
  "IoT Battery Storage Management",
  "Smart EV Charging Station Monitor",
  "IoT Fuel Level Monitoring System",
  "Smart Gas Station Safety System",
  "IoT Restaurant Kitchen Monitor",
  "Smart Food Storage Temperature System",
  "IoT Cold Chain Logistics Monitor",
  "Smart Pharmaceutical Storage System",
  "IoT Vaccine Temperature Tracker",
  "Smart Blood Bank Storage Monitor",
  "IoT Organ Transport Container",
  "Smart Laboratory Sample Tracker"
];

// ============ INTERNSHIP PROJECTS (100+) ============
const internshipNames = [
  "MERN Stack Developer Internship Project",
  "Python AI/ML Developer Internship Project",
  "Full Stack Web Development Internship Capstone",
  "Data Analytics Internship Project with Python",
  "Django REST API Internship Project",
  "React.js Frontend Development Internship Project",
  "Node.js Backend Development Internship Project",
  "AI Chatbot Development Internship Project",
  "Machine Learning Internship Capstone Project",
  "Cloud Deployment (AWS/Azure) Internship Project",
  "Cybersecurity Fundamentals Internship Project",
  "UI/UX Design Internship Portfolio Project",
  "Flutter Mobile App Development Internship",
  "Java Spring Boot Backend Internship Project",
  "DevOps Pipeline Automation Internship Project",
  "Blockchain Development Internship Project",
  "Data Science & Visualization Internship Project",
  "Deep Learning Internship Capstone Project",
  "Computer Vision Internship Project",
  "NLP & Text Analytics Internship Project",
  "React Native Cross-Platform App Internship",
  "Angular Frontend Development Internship",
  "Vue.js Interactive Dashboard Internship",
  "GraphQL & Apollo Server Internship Project",
  "Microservices Architecture Internship Project",
  "Docker & Kubernetes Deployment Internship",
  "CI/CD Pipeline Implementation Internship",
  "Testing Automation (Selenium/JUnit) Internship",
  "API Development & Integration Internship",
  "Database Design & Optimization Internship",
  "MongoDB & NoSQL Database Internship Project",
  "PostgreSQL Advanced Queries Internship",
  "Redis Caching Implementation Internship",
  "Elasticsearch & Logging Internship Project",
  "RabbitMQ Message Queue Implementation",
  "Kafka Stream Processing Internship Project",
  "Spark Data Processing Internship Project",
  "Hadoop Big Data Analytics Internship",
  "TensorFlow Model Deployment Internship",
  "PyTorch Deep Learning Implementation",
  "Scikit-Learn ML Pipeline Internship",
  "Pandas Data Analysis Internship Project",
  "NumPy Scientific Computing Internship",
  "Matplotlib & Seaborn Visualization Internship",
  "Power BI Business Intelligence Internship",
  "Tableau Data Dashboard Internship Project",
  "Looker Studio Data Visualization Internship",
  "QlikView Data Analytics Internship Project",
  "SAS Programming & Analytics Internship",
  "R Programming Statistical Analysis Internship",
  "Excel Advanced Analytics Internship Project",
  "VBA Automation Internship Project",
  "Google Apps Script Development Internship",
  "WordPress Theme Development Internship",
  "Shopify E-Commerce Development Internship",
  "Magento Custom Module Development Internship",
  "WooCommerce Plugin Development Internship",
  "Custom CRM Development Internship Project",
  "ERP System Implementation Internship",
  "HRMS Portal Development Internship",
  "LMS Platform Development Internship Project",
  "CMS Customization & Development Internship",
  "Payment Gateway Integration Internship",
  "Razorpay & Stripe API Implementation",
  "Google Maps API Integration Internship",
  "Weather API & Data Processing Internship",
  "Social Media API Integration Internship",
  "Twitter/X API Data Analysis Internship",
  "Instagram API Integration Internship Project",
  "Facebook Graph API Implementation",
  "LinkedIn API Professional Network Analysis",
  "YouTube API Data Analytics Internship",
  "Spotify API Music Recommendation Internship",
  "Twilio SMS & Call Automation Internship",
  "Email Marketing Automation (Mailchimp) Internship",
  "Chat Application (Socket.io) Internship Project",
  "Video Calling (WebRTC) Implementation Internship",
  "File Upload & Processing Pipeline Internship",
  "Image Processing API Development Internship",
  "PDF Generation & Processing Internship Project",
  "Excel Report Generation Automation Internship",
  "Data Scraping & Web Crawling Internship",
  "BeautifulSoup & Scrapy Project Internship",
  "Selenium Web Automation Internship Project",
  "Playwright Testing Automation Internship",
  "Jest Unit Testing Internship Project",
  "Cypress E2E Testing Internship Project",
  "Bug Tracking System Implementation Internship",
  "Error Monitoring (Sentry) Integration Internship",
  "Performance Monitoring & Optimization Internship",
  "SEO Optimization & Analytics Internship",
  "Google Analytics 4 Implementation Internship",
  "GTM (Google Tag Manager) Setup Internship",
  "A/B Testing & Experimentation Internship",
  "User Analytics & Heatmap Implementation",
  "Hotjar & User Behavior Analysis Internship",
  "Mixpanel Product Analytics Internship",
  "Amplitude Event Tracking Internship Project",
  "Segment Data Integration Internship Project",
  "OpenAI GPT Integration & Fine-Tuning Internship",
  "LangChain LLM Application Development Internship",
  "Vector Database (Pinecone) Implementation",
  "RAG (Retrieval-Augmented Generation) Internship",
  "Prompt Engineering & Optimization Internship"
];

// ============ HELPER FUNCTIONS ============
function toCategoryList(names, category) {
  return names.map((name) => ({ name, category }));
}

// ============ GENERATE PROJECTS ============
const rawList = [
  ...toCategoryList(websiteNames, "Website"),
  ...toCategoryList(mobileNames, "Mobile / App"),
  ...toCategoryList(iotNames, "IoT"),
  ...toCategoryList(internshipNames, "Internship"),
];

// Ensure we have enough projects - duplicate if needed to reach 500+
let finalRawList = [...rawList];
while (finalRawList.length < 500) {
  // Add variations with numbering
  const category = finalRawList.length % 4 === 0 ? "Website" : 
                  finalRawList.length % 4 === 1 ? "Mobile / App" :
                  finalRawList.length % 4 === 2 ? "IoT" : "Internship";
  const baseName = category === "Website" ? "Advanced " :
                  category === "Mobile / App" ? "Pro " :
                  category === "IoT" ? "Smart " : "Enterprise ";
  finalRawList.push({
    name: `${baseName}Project ${finalRawList.length + 1}`,
    category: category
  });
}

export const projects = finalRawList.map((p, idx) => ({
  id: idx + 1,
  price: p.category === "Internship" ? "₹6,000" : "₹13,000",
  ...p,
}));

// ============ CATEGORIES WITH COUNTS ============
export const CATEGORIES = [
  { key: "All", label: "All Projects", count: projects.length },
  {
    key: "Website",
    label: "Website",
    count: projects.filter((p) => p.category === "Website").length,
  },
  {
    key: "Mobile / App",
    label: "Mobile / App",
    count: projects.filter((p) => p.category === "Mobile / App").length,
  },
  {
    key: "IoT",
    label: "IoT",
    count: projects.filter((p) => p.category === "IoT").length,
  },
  {
    key: "Internship",
    label: "Internship Projects",
    count: projects.filter((p) => p.category === "Internship").length,
  },
];

// ============ STATISTICS ============
export const PROJECT_STATS = {
  total: projects.length,
  byCategory: {
    Website: projects.filter(p => p.category === "Website").length,
    "Mobile / App": projects.filter(p => p.category === "Mobile / App").length,
    IoT: projects.filter(p => p.category === "IoT").length,
    Internship: projects.filter(p => p.category === "Internship").length,
  },
  pricing: {
    finalYear: "₹13,000",
    internship: "₹6,000",
  }
};

// ============ EXPORT FUNCTIONS ============
export const getProjectsByCategory = (category) => {
  if (category === "All") return projects;
  return projects.filter(p => p.category === category);
};

export const getProjectById = (id) => {
  return projects.find(p => p.id === id);
};

export const searchProjects = (query) => {
  return projects.filter(p => 
    p.name.toLowerCase().includes(query.toLowerCase())
  );
};